export const countries= [
  { id: 'AD', name: 'Andorra', phone: '376' },
  {
    id: 'AE',
    name: 'United Arab Emirates',
    phone: '971',
  },
  { id: 'AF', name: 'Afghanistan', phone: '93' },
  {
    id: 'AG',
    name: 'Antigua and Barbuda',
    phone: '1-268',
  },
  { id: 'AI', name: 'Anguilla', phone: '1-264' },
  { id: 'AL', name: 'Albania', phone: '355' },
  { id: 'AM', name: 'Armenia', phone: '374' },
  { id: 'AO', name: 'Angola', phone: '244' },
  { id: 'AQ', name: 'Antarctica', phone: '672' },
  { id: 'AR', name: 'Argentina', phone: '54' },
  { id: 'AS', name: 'American Samoa', phone: '1-684' },
  { id: 'AT', name: 'Austria', phone: '43' },
  {
    id: 'AU',
    name: 'Australia',
    phone: '61',
    suggested: true,
  },
  { id: 'AW', name: 'Aruba', phone: '297' },
  { id: 'AX', name: 'Alland Islands', phone: '358' },
  { id: 'AZ', name: 'Azerbaijan', phone: '994' },
  {
    id: 'BA',
    name: 'Bosnia and Herzegovina',
    phone: '387',
  },
  { id: 'BB', name: 'Barbados', phone: '1-246' },
  { id: 'BD', name: 'Bangladesh', phone: '880' },
  { id: 'BE', name: 'Belgium', phone: '32' },
  { id: 'BF', name: 'Burkina Faso', phone: '226' },
  { id: 'BG', name: 'Bulgaria', phone: '359' },
  { id: 'BH', name: 'Bahrain', phone: '973' },
  { id: 'BI', name: 'Burundi', phone: '257' },
  { id: 'BJ', name: 'Benin', phone: '229' },
  { id: 'BL', name: 'Saint Barthelemy', phone: '590' },
  { id: 'BM', name: 'Bermuda', phone: '1-441' },
  { id: 'BN', name: 'Brunei Darussalam', phone: '673' },
  { id: 'BO', name: 'Bolivia', phone: '591' },
  { id: 'BR', name: 'Brazil', phone: '55' },
  { id: 'BS', name: 'Bahamas', phone: '1-242' },
  { id: 'BT', name: 'Bhutan', phone: '975' },
  { id: 'BV', name: 'Bouvet Island', phone: '47' },
  { id: 'BW', name: 'Botswana', phone: '267' },
  { id: 'BY', name: 'Belarus', phone: '375' },
  { id: 'BZ', name: 'Belize', phone: '501' },
  {
    id: 'CA',
    name: 'Canada',
    phone: '1',
    suggested: true,
  },
  {
    id: 'CC',
    name: 'Cocos (Keeling) Islands',
    phone: '61',
  },
  {
    id: 'CD',
    name: 'Congo, Democratic Republic of the',
    phone: '243',
  },
  {
    id: 'CF',
    name: 'Central African Republic',
    phone: '236',
  },
  {
    id: 'CG',
    name: 'Congo, Republic of the',
    phone: '242',
  },
  { id: 'CH', name: 'Switzerland', phone: '41' },
  { id: 'CI', name: 'Cote d\'Ivoire', phone: '225' },
  { id: 'CK', name: 'Cook Islands', phone: '682' },
  { id: 'CL', name: 'Chile', phone: '56' },
  { id: 'CM', name: 'Cameroon', phone: '237' },
  { id: 'CN', name: 'China', phone: '86' },
  { id: 'CO', name: 'Colombia', phone: '57' },
  { id: 'CR', name: 'Costa Rica', phone: '506' },
  { id: 'CU', name: 'Cuba', phone: '53' },
  { id: 'CV', name: 'Cape Verde', phone: '238' },
  { id: 'CW', name: 'Curacao', phone: '599' },
  { id: 'CX', name: 'Christmas Island', phone: '61' },
  { id: 'CY', name: 'Cyprus', phone: '357' },
  { id: 'CZ', name: 'Czech Republic', phone: '420' },
  {
    id: 'DE',
    name: 'Germany',
    phone: '49',
    suggested: true,
  },
  { id: 'DJ', name: 'Djibouti', phone: '253' },
  { id: 'DK', name: 'Denmark', phone: '45' },
  { id: 'DM', name: 'Dominica', phone: '1-767' },
  {
    id: 'DO',
    name: 'Dominican Republic',
    phone: '1-809',
  },
  { id: 'DZ', name: 'Algeria', phone: '213' },
  { id: 'EC', name: 'Ecuador', phone: '593' },
  { id: 'EE', name: 'Estonia', phone: '372' },
  { id: 'EG', name: 'Egypt', phone: '20' },
  { id: 'EH', name: 'Western Sahara', phone: '212' },
  { id: 'ER', name: 'Eritrea', phone: '291' },
  { id: 'ES', name: 'Spain', phone: '34' },
  { id: 'ET', name: 'Ethiopia', phone: '251' },
  { id: 'FI', name: 'Finland', phone: '358' },
  { id: 'FJ', name: 'Fiji', phone: '679' },
  {
    id: 'FK',
    name: 'Falkland Islands (Malvinas)',
    phone: '500',
  },
  {
    id: 'FM',
    name: 'Micronesia, Federated States of',
    phone: '691',
  },
  { id: 'FO', name: 'Faroe Islands', phone: '298' },
  {
    id: 'FR',
    name: 'France',
    phone: '33',
    suggested: true,
  },
  { id: 'GA', name: 'Gabon', phone: '241' },
  { id: 'GB', name: 'United Kingdom', phone: '44' },
  { id: 'GD', name: 'Grenada', phone: '1-473' },
  { id: 'GE', name: 'Georgia', phone: '995' },
  { id: 'GF', name: 'French Guiana', phone: '594' },
  { id: 'GG', name: 'Guernsey', phone: '44' },
  { id: 'GH', name: 'Ghana', phone: '233' },
  { id: 'GI', name: 'Gibraltar', phone: '350' },
  { id: 'GL', name: 'Greenland', phone: '299' },
  { id: 'GM', name: 'Gambia', phone: '220' },
  { id: 'GN', name: 'Guinea', phone: '224' },
  { id: 'GP', name: 'Guadeloupe', phone: '590' },
  { id: 'GQ', name: 'Equatorial Guinea', phone: '240' },
  { id: 'GR', name: 'Greece', phone: '30' },
  {
    id: 'GS',
    name: 'South Georgia and the South Sandwich Islands',
    phone: '500',
  },
  { id: 'GT', name: 'Guatemala', phone: '502' },
  { id: 'GU', name: 'Guam', phone: '1-671' },
  { id: 'GW', name: 'Guinea-Bissau', phone: '245' },
  { id: 'GY', name: 'Guyana', phone: '592' },
  { id: 'HK', name: 'Hong Kong', phone: '852' },
  {
    id: 'HM',
    name: 'Heard Island and McDonald Islands',
    phone: '672',
  },
  { id: 'HN', name: 'Honduras', phone: '504' },
  { id: 'HR', name: 'Croatia', phone: '385' },
  { id: 'HT', name: 'Haiti', phone: '509' },
  { id: 'HU', name: 'Hungary', phone: '36' },
  { id: 'ID', name: 'Indonesia', phone: '62' },
  { id: 'IE', name: 'Ireland', phone: '353' },
  { id: 'IL', name: 'Israel', phone: '972' },
  { id: 'IM', name: 'Isle of Man', phone: '44' },
  { id: 'IN', name: 'India', phone: '91' },
  {
    id: 'IO',
    name: 'British Indian Ocean Territory',
    phone: '246',
  },
  { id: 'IQ', name: 'Iraq', phone: '964' },
  {
    id: 'IR',
    name: 'Iran, Islamic Republic of',
    phone: '98',
  },
  { id: 'IS', name: 'Iceland', phone: '354' },
  { id: 'IT', name: 'Italy', phone: '39' },
  { id: 'JE', name: 'Jersey', phone: '44' },
  { id: 'JM', name: 'Jamaica', phone: '1-876' },
  { id: 'JO', name: 'Jordan', phone: '962' },
  {
    id: 'JP',
    name: 'Japan',
    phone: '81',
    suggested: true,
  },
  { id: 'KE', name: 'Kenya', phone: '254' },
  { id: 'KG', name: 'Kyrgyzstan', phone: '996' },
  { id: 'KH', name: 'Cambodia', phone: '855' },
  { id: 'KI', name: 'Kiribati', phone: '686' },
  { id: 'KM', name: 'Comoros', phone: '269' },
  {
    id: 'KN',
    name: 'Saint Kitts and Nevis',
    phone: '1-869',
  },
  {
    id: 'KP',
    name: 'Korea, Democratic People\'s Republic of',
    phone: '850',
  },
  { id: 'KR', name: 'Korea, Republic of', phone: '82' },
  { id: 'KW', name: 'Kuwait', phone: '965' },
  { id: 'KY', name: 'Cayman Islands', phone: '1-345' },
  { id: 'KZ', name: 'Kazakhstan', phone: '7' },
  {
    id: 'LA',
    name: 'Lao People\'s Democratic Republic',
    phone: '856',
  },
  { id: 'LB', name: 'Lebanon', phone: '961' },
  { id: 'LC', name: 'Saint Lucia', phone: '1-758' },
  { id: 'LI', name: 'Liechtenstein', phone: '423' },
  { id: 'LK', name: 'Sri Lanka', phone: '94' },
  { id: 'LR', name: 'Liberia', phone: '231' },
  { id: 'LS', name: 'Lesotho', phone: '266' },
  { id: 'LT', name: 'Lithuania', phone: '370' },
  { id: 'LU', name: 'Luxembourg', phone: '352' },
  { id: 'LV', name: 'Latvia', phone: '371' },
  { id: 'LY', name: 'Libya', phone: '218' },
  { id: 'MA', name: 'Morocco', phone: '212' },
  { id: 'MC', name: 'Monaco', phone: '377' },
  {
    id: 'MD',
    name: 'Moldova, Republic of',
    phone: '373',
  },
  { id: 'ME', name: 'Montenegro', phone: '382' },
  {
    id: 'MF',
    name: 'Saint Martin (French part)',
    phone: '590',
  },
  { id: 'MG', name: 'Madagascar', phone: '261' },
  { id: 'MH', name: 'Marshall Islands', phone: '692' },
  {
    id: 'MK',
    name: 'Macedonia, the Former Yugoslav Republic of',
    phone: '389',
  },
  { id: 'ML', name: 'Mali', phone: '223' },
  { id: 'MM', name: 'Myanmar', phone: '95' },
  { id: 'MN', name: 'Mongolia', phone: '976' },
  { id: 'MO', name: 'Macao', phone: '853' },
  {
    id: 'MP',
    name: 'Northern Mariana Islands',
    phone: '1-670',
  },
  { id: 'MQ', name: 'Martinique', phone: '596' },
  { id: 'MR', name: 'Mauritania', phone: '222' },
  { id: 'MS', name: 'Montserrat', phone: '1-664' },
  { id: 'MT', name: 'Malta', phone: '356' },
  { id: 'MU', name: 'Mauritius', phone: '230' },
  { id: 'MV', name: 'Maldives', phone: '960' },
  { id: 'MW', name: 'Malawi', phone: '265' },
  { id: 'MX', name: 'Mexico', phone: '52' },
  { id: 'MY', name: 'Malaysia', phone: '60' },
  { id: 'MZ', name: 'Mozambique', phone: '258' },
  { id: 'NA', name: 'Namibia', phone: '264' },
  { id: 'NC', name: 'New Caledonia', phone: '687' },
  { id: 'NE', name: 'Niger', phone: '227' },
  { id: 'NF', name: 'Norfolk Island', phone: '672' },
  { id: 'NG', name: 'Nigeria', phone: '234' },
  { id: 'NI', name: 'Nicaragua', phone: '505' },
  { id: 'NL', name: 'Netherlands', phone: '31' },
  { id: 'NO', name: 'Norway', phone: '47' },
  { id: 'NP', name: 'Nepal', phone: '977' },
  { id: 'NR', name: 'Nauru', phone: '674' },
  { id: 'NU', name: 'Niue', phone: '683' },
  { id: 'NZ', name: 'New Zealand', phone: '64' },
  { id: 'OM', name: 'Oman', phone: '968' },
  { id: 'PA', name: 'Panama', phone: '507' },
  { id: 'PE', name: 'Peru', phone: '51' },
  { id: 'PF', name: 'French Polynesia', phone: '689' },
  { id: 'PG', name: 'Papua New Guinea', phone: '675' },
  { id: 'PH', name: 'Philippines', phone: '63' },
  { id: 'PK', name: 'Pakistan', phone: '92' },
  { id: 'PL', name: 'Poland', phone: '48' },
  {
    id: 'PM',
    name: 'Saint Pierre and Miquelon',
    phone: '508',
  },
  { id: 'PN', name: 'Pitcairn', phone: '870' },
  { id: 'PR', name: 'Puerto Rico', phone: '1' },
  {
    id: 'PS',
    name: 'Palestine, State of',
    phone: '970',
  },
  { id: 'PT', name: 'Portugal', phone: '351' },
  { id: 'PW', name: 'Palau', phone: '680' },
  { id: 'PY', name: 'Paraguay', phone: '595' },
  { id: 'QA', name: 'Qatar', phone: '974' },
  { id: 'RE', name: 'Reunion', phone: '262' },
  { id: 'RO', name: 'Romania', phone: '40' },
  { id: 'RS', name: 'Serbia', phone: '381' },
  { id: 'RU', name: 'Russian Federation', phone: '7' },
  { id: 'RW', name: 'Rwanda', phone: '250' },
  { id: 'SA', name: 'Saudi Arabia', phone: '966' },
  { id: 'SB', name: 'Solomon Islands', phone: '677' },
  { id: 'SC', name: 'Seychelles', phone: '248' },
  { id: 'SD', name: 'Sudan', phone: '249' },
  { id: 'SE', name: 'Sweden', phone: '46' },
  { id: 'SG', name: 'Singapore', phone: '65' },
  { id: 'SH', name: 'Saint Helena', phone: '290' },
  { id: 'SI', name: 'Slovenia', phone: '386' },
  {
    id: 'SJ',
    name: 'Svalbard and Jan Mayen',
    phone: '47',
  },
  { id: 'SK', name: 'Slovakia', phone: '421' },
  { id: 'SL', name: 'Sierra Leone', phone: '232' },
  { id: 'SM', name: 'San Marino', phone: '378' },
  { id: 'SN', name: 'Senegal', phone: '221' },
  { id: 'SO', name: 'Somalia', phone: '252' },
  { id: 'SR', name: 'Suriname', phone: '597' },
  { id: 'SS', name: 'South Sudan', phone: '211' },
  {
    id: 'ST',
    name: 'Sao Tome and Principe',
    phone: '239',
  },
  { id: 'SV', name: 'El Salvador', phone: '503' },
  {
    id: 'SX',
    name: 'Sint Maarten (Dutch part)',
    phone: '1-721',
  },
  {
    id: 'SY',
    name: 'Syrian Arab Republic',
    phone: '963',
  },
  { id: 'SZ', name: 'Swaziland', phone: '268' },
  {
    id: 'TC',
    name: 'Turks and Caicos Islands',
    phone: '1-649',
  },
  { id: 'TD', name: 'Chad', phone: '235' },
  {
    id: 'TF',
    name: 'French Southern Territories',
    phone: '262',
  },
  { id: 'TG', name: 'Togo', phone: '228' },
  { id: 'TH', name: 'Thailand', phone: '66' },
  { id: 'TJ', name: 'Tajikistan', phone: '992' },
  { id: 'TK', name: 'Tokelau', phone: '690' },
  { id: 'TL', name: 'Timor-Leste', phone: '670' },
  { id: 'TM', name: 'Turkmenistan', phone: '993' },
  { id: 'TN', name: 'Tunisia', phone: '216' },
  { id: 'TO', name: 'Tonga', phone: '676' },
  { id: 'TR', name: 'Turkey', phone: '90' },
  {
    id: 'TT',
    name: 'Trinidad and Tobago',
    phone: '1-868',
  },
  { id: 'TV', name: 'Tuvalu', phone: '688' },
  {
    id: 'TW',
    name: 'Taiwan, Province of China',
    phone: '886',
  },
  {
    id: 'TZ',
    name: 'United Republic of Tanzania',
    phone: '255',
  },
  { id: 'UA', name: 'Ukraine', phone: '380' },
  { id: 'UG', name: 'Uganda', phone: '256' },
  {
    id: 'US',
    name: 'United States',
    phone: '1',
    suggested: true,
  },
  { id: 'UY', name: 'Uruguay', phone: '598' },
  { id: 'UZ', name: 'Uzbekistan', phone: '998' },
  {
    id: 'VA',
    name: 'Holy See (Vatican City State)',
    phone: '379',
  },
  {
    id: 'VC',
    name: 'Saint Vincent and the Grenadines',
    phone: '1-784',
  },
  { id: 'VE', name: 'Venezuela', phone: '58' },
  {
    id: 'VG',
    name: 'British Virgin Islands',
    phone: '1-284',
  },
  {
    id: 'VI',
    name: 'US Virgin Islands',
    phone: '1-340',
  },
  { id: 'VN', name: 'Vietnam', phone: '84' },
  { id: 'VU', name: 'Vanuatu', phone: '678' },
  { id: 'WF', name: 'Wallis and Futuna', phone: '681' },
  { id: 'WS', name: 'Samoa', phone: '685' },
  { id: 'XK', name: 'Kosovo', phone: '383' },
  { id: 'YE', name: 'Yemen', phone: '967' },
  { id: 'YT', name: 'Mayotte', phone: '262' },
  { id: 'ZA', name: 'South Africa', phone: '27' },
  { id: 'ZM', name: 'Zambia', phone: '260' },
  { id: 'ZW', name: 'Zimbabwe', phone: '263' },
];